on:
  push:
    branches: [ 21w17a ]
  pull_request:
    branches: [ 21w17a ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      - name: Test
      run: |
        ./gradlew download
        ./gradlew mergeJars
        ./gradlew mapNamedJar
        ./gradlew decompileCFR
